name = "spark_crypto_utils"
version = "1.0.0"
description = "SPARK Ada cryptographic utilities: nonce generation, Shamir secret sharing, zeroization"
licenses = "Apache-2.0"
authors = ["AnubisQuantumCipher <sic.tau@pm.me>"]
maintainers = ["AnubisQuantumCipher <sic.tau@pm.me>"]
website = "https://github.com/AnubisQuantumCipher/spark_crypto_utils"
tags = ["cryptography", "shamir", "nonce", "spark", "utilities"]
project-files = ["spark_crypto_utils.gpr"]

long-description = """
Cryptographic utilities: nonce generation, Shamir (k,n) threshold secret sharing, key wrapping, zeroization.
"""
